clean:
	rm -rf sml/*~ sml/MLB
	rm -rf *~
	rm -rf dist/*~ dist/contrib/*~ dist/css/*~ dist/js/*~ dist/contrib/sml/*~ dist/contrib/sml/css/*~ dist/contrib/sml/js/*~
	rm -rf dist/contrib/fundamental/*~ dist/contrib/fundamental/css/*~ dist/contrib/fundamental/js/*~