(* quot (minInt, ~1) overflows and must raise Overflow rather than
 * return minInt or trap in the division instruction; rem (minInt, ~1)
 * is 0. *)
fun p s = print (s ^ "\n")
fun t f = (f ()) handle Overflow => "Overflow" | Div => "Div"
val () = p ("Int quot: " ^ t (fn () => Int.toString (Int.quot (valOf Int.minInt, ~1))))
val () = p ("Int rem: " ^ t (fn () => Int.toString (Int.rem (valOf Int.minInt, ~1))))
val () = p ("Int quot 7 ~2: " ^ t (fn () => Int.toString (Int.quot (7, ~2))) ^ " rem " ^ t (fn () => Int.toString (Int.rem (7, ~2))))
val () = p ("Int quot ~7 2: " ^ t (fn () => Int.toString (Int.quot (~7, 2))) ^ " rem " ^ t (fn () => Int.toString (Int.rem (~7, 2))))
val () = p ("Int quot by 0: " ^ t (fn () => Int.toString (Int.quot (1, 0))))
val () = p ("Int31 quot: " ^ t (fn () => Int31.toString (Int31.quot (valOf Int31.minInt, ~1))))
val () = p ("Int31 rem: " ^ t (fn () => Int31.toString (Int31.rem (valOf Int31.minInt, ~1))))
val () = p ("Int32 quot: " ^ t (fn () => Int32.toString (Int32.quot (valOf Int32.minInt, ~1))))
val () = p ("Int32 rem: " ^ t (fn () => Int32.toString (Int32.rem (valOf Int32.minInt, ~1))))
val () = p ("Int63 quot: " ^ t (fn () => Int63.toString (Int63.quot (valOf Int63.minInt, ~1))))
val () = p ("Int63 rem: " ^ t (fn () => Int63.toString (Int63.rem (valOf Int63.minInt, ~1))))
val () = p ("Int64 quot: " ^ t (fn () => Int64.toString (Int64.quot (valOf Int64.minInt, ~1))))
val () = p ("Int64 rem: " ^ t (fn () => Int64.toString (Int64.rem (valOf Int64.minInt, ~1))))
val () = p ("Int64 quot 7 ~2: " ^ t (fn () => Int64.toString (Int64.quot (7, ~2))) ^ " rem " ^ t (fn () => Int64.toString (Int64.rem (~7, 2))))
val () = p ("Int32 quot minInt 1: " ^ t (fn () => Int32.toString (Int32.quot (valOf Int32.minInt, 1))))
