(* Word8.toLargeX sign-extends to the whole of LargeWord. *)
fun p s = print (s ^ "\n")
val () = p ("toLargeX E2 = " ^ LargeWord.toString (Word8.toLargeX 0wxE2))
val () = p ("toLargeX 7F = " ^ LargeWord.toString (Word8.toLargeX 0wx7F))
val () = p ("toLargeX FF = " ^ LargeWord.toString (Word8.toLargeX 0wxFF))
val () = p ("toLarge FF = " ^ LargeWord.toString (Word8.toLarge 0wxFF))
val () = p ("toIntX E2 = " ^ Int.toString (Word8.toIntX 0wxE2))
val () = p ("via large: " ^ Int.toString (Int.fromLarge (LargeWord.toLargeIntX (Word8.toLargeX 0wxE2))))
val () = p ("toLargeIntX FF = " ^ LargeInt.toString (Word8.toLargeIntX 0wxFF))
