(* Scanning a numeral too large for the word raises Overflow. *)
fun p s = print (s ^ "\n")
fun t f = (case f () of SOME s => s | NONE => "NONE") handle Overflow => "Overflow"
val () = p ("Word DEC: " ^ t (fn () => Option.map Word.toString (StringCvt.scanString (Word.scan StringCvt.DEC) (Word.fmt StringCvt.DEC (Word.notb 0w0) ^ "0"))))
val () = p ("Word HEX: " ^ t (fn () => Option.map Word.toString (StringCvt.scanString (Word.scan StringCvt.HEX) (Word.fmt StringCvt.HEX (Word.notb 0w0) ^ "0"))))
val () = p ("Word fromString: " ^ t (fn () => Option.map Word.toString (Word.fromString (Word.toString (Word.notb 0w0) ^ "0"))))
val () = p ("Word max: " ^ t (fn () => Option.map Word63.toString (Word63.fromString (Word63.toString (Word63.notb 0w0)))))
val () = p ("Word max+1 DEC: " ^ t (fn () => Option.map Word63.toString (StringCvt.scanString (Word63.scan StringCvt.DEC) "9223372036854775808")))
val () = p ("Word 2^63-1 DEC: " ^ t (fn () => Option.map Word.toString (StringCvt.scanString (Word.scan StringCvt.DEC) "9223372036854775807")))
val () = p ("Word8: " ^ t (fn () => Option.map Word8.toString (Word8.fromString "100")))
val () = p ("Word8 ok: " ^ t (fn () => Option.map Word8.toString (Word8.fromString "FF")))
val () = p ("Word8 DEC 256: " ^ t (fn () => Option.map Word8.toString (StringCvt.scanString (Word8.scan StringCvt.DEC) "256")))
val () = p ("Word8 DEC 255: " ^ t (fn () => Option.map Word8.toString (StringCvt.scanString (Word8.scan StringCvt.DEC) "255")))
val () = p ("Word31: " ^ t (fn () => Option.map Word31.toString (Word31.fromString "80000000")))
val () = p ("Word31 ok: " ^ t (fn () => Option.map Word31.toString (Word31.fromString "7FFFFFFF")))
val () = p ("Word32: " ^ t (fn () => Option.map Word32.toString (Word32.fromString "100000000")))
val () = p ("Word32 ok: " ^ t (fn () => Option.map Word32.toString (Word32.fromString "FFFFFFFF")))
val () = p ("Word32 DEC: " ^ t (fn () => Option.map Word32.toString (StringCvt.scanString (Word32.scan StringCvt.DEC) "4294967296")))
val () = p ("Word63: " ^ t (fn () => Option.map Word63.toString (Word63.fromString "8000000000000000")))
val () = p ("Word63 ok: " ^ t (fn () => Option.map Word63.toString (Word63.fromString "7FFFFFFFFFFFFFFF")))
val () = p ("Word64: " ^ t (fn () => Option.map Word64.toString (Word64.fromString "10000000000000000")))
val () = p ("Word64 ok: " ^ t (fn () => Option.map Word64.toString (Word64.fromString "FFFFFFFFFFFFFFFF")))
val () = p ("Word64 DEC: " ^ t (fn () => Option.map Word64.toString (StringCvt.scanString (Word64.scan StringCvt.DEC) "18446744073709551616")))
val () = p ("Word64 DEC ok: " ^ t (fn () => Option.map Word64.toString (StringCvt.scanString (Word64.scan StringCvt.DEC) "18446744073709551615")))
val () = p ("Word16: " ^ t (fn () => Option.map Word16.toString (Word16.fromString "10000")))
val () = p ("Word16 ok: " ^ t (fn () => Option.map Word16.toString (Word16.fromString "FFFF")))
