infix 6 + -
infix 4 <
infixr 5 ::
infix 3 :=
fun !(x:'a ref):'a = prim("!",x)
fun op := (x:'a ref,y:'a):unit=prim(":=",(x,y))
fun build__noinline(n:int,xs) = if n < 1 then xs else build__noinline(n-1,n::xs)
fun sum__noinline(nil,acc:int) = acc | sum__noinline(x::xs,acc)=sum__noinline(xs,acc+x)
val global = ref(build__noinline(10,nil))
fun mutate__noinline(n:int) = if n < 1 then () else
  (global := build__noinline(n,nil); mutate__noinline(n-1))
fun roots__noinline(n:int) = let
  val x0=build__noinline(n+0,nil)
  val x1=build__noinline(n+1,nil)
  val x2=build__noinline(n+2,nil)
  val x3=build__noinline(n+3,nil)
  val x4=build__noinline(n+4,nil)
  val x5=build__noinline(n+5,nil)
  val x6=build__noinline(n+6,nil)
  val x7=build__noinline(n+7,nil)
  val x8=build__noinline(n+8,nil)
  val x9=build__noinline(n+9,nil)
  val x10=build__noinline(n+10,nil)
  val x11=build__noinline(n+11,nil)
  val x12=build__noinline(n+12,nil)
  val x13=build__noinline(n+13,nil)
  val x14=build__noinline(n+14,nil)
  val x15=build__noinline(n+15,nil)
  val x16=build__noinline(n+16,nil)
  val x17=build__noinline(n+17,nil)
  val x18=build__noinline(n+18,nil)
  val x19=build__noinline(n+19,nil)
  val x20=build__noinline(n+20,nil)
  val x21=build__noinline(n+21,nil)
  val x22=build__noinline(n+22,nil)
  val x23=build__noinline(n+23,nil)
  val x24=build__noinline(n+24,nil)
  val x25=build__noinline(n+25,nil)
  val x26=build__noinline(n+26,nil)
  val x27=build__noinline(n+27,nil)
  val x28=build__noinline(n+28,nil)
  val x29=build__noinline(n+29,nil)
  val x30=build__noinline(n+30,nil)
  val x31=build__noinline(n+31,nil)
  val x32=build__noinline(n+32,nil)
  val x33=build__noinline(n+33,nil)
  val x34=build__noinline(n+34,nil)
  val x35=build__noinline(n+35,nil)
  val x36=build__noinline(n+36,nil)
  val x37=build__noinline(n+37,nil)
  val x38=build__noinline(n+38,nil)
  val x39=build__noinline(n+39,nil)
  val ()=mutate__noinline 100
  in sum__noinline(x0,0)+sum__noinline(x1,0)+sum__noinline(x2,0)+sum__noinline(x3,0)+sum__noinline(x4,0)+sum__noinline(x5,0)+sum__noinline(x6,0)+sum__noinline(x7,0)+sum__noinline(x8,0)+sum__noinline(x9,0)+sum__noinline(x10,0)+sum__noinline(x11,0)+sum__noinline(x12,0)+sum__noinline(x13,0)+sum__noinline(x14,0)+sum__noinline(x15,0)+sum__noinline(x16,0)+sum__noinline(x17,0)+sum__noinline(x18,0)+sum__noinline(x19,0)+sum__noinline(x20,0)+sum__noinline(x21,0)+sum__noinline(x22,0)+sum__noinline(x23,0)+sum__noinline(x24,0)+sum__noinline(x25,0)+sum__noinline(x26,0)+sum__noinline(x27,0)+sum__noinline(x28,0)+sum__noinline(x29,0)+sum__noinline(x30,0)+sum__noinline(x31,0)+sum__noinline(x32,0)+sum__noinline(x33,0)+sum__noinline(x34,0)+sum__noinline(x35,0)+sum__noinline(x36,0)+sum__noinline(x37,0)+sum__noinline(x38,0)+sum__noinline(x39,0) end
val n=roots__noinline 1
val final=sum__noinline(!global,0)
val _:unit=prim("printStringML",if 11479 < n andalso n < 11481 andalso 0 < final andalso final < 2 then "OK\n" else "BAD\n")
