(* This file is auto-generated with Tools/GenOpcodes; it is *)
(* based on the file /home/mael/mlkit/kit/src/Compiler/Backend/KAM/KamInsts.spec *)
signature OPCODES_KAM = 
  sig
    val ALLOC_N : int 
    val ALLOC_IF_INF_N : int 
    val ALLOC_SAT_INF_N : int 
    val ALLOC_SAT_IF_INF_N : int 
    val ALLOC_ATBOT_N : int 
    val BLOCK_ALLOC_2 : int 
    val BLOCK_ALLOC_N : int 
    val BLOCK_ALLOC_IF_INF_N : int 
    val BLOCK_ALLOC_SAT_INF_N : int 
    val BLOCK_N : int 
    val BLOCK_ALLOC_SAT_IF_INF_N : int 
    val BLOCK_ALLOC_ATBOT_N : int 
    val CLEAR_ATBOT_BIT : int 
    val SET_ATBOT_BIT : int 
    val SET_BIT_30 : int 
    val SET_BIT_31 : int 
    val CLEAR_BIT_30_AND_31 : int 
    val UB_TAG_CON : int 
    val SELECT_STACK_M1 : int 
    val SELECT_STACK_M2 : int 
    val SELECT_STACK_M3 : int 
    val SELECT_STACK_M4 : int 
    val SELECT_STACK_N : int 
    val SELECT_ENV_N : int 
    val SELECT_0 : int 
    val SELECT_1 : int 
    val SELECT_2 : int 
    val SELECT_3 : int 
    val SELECT_N : int 
    val STORE_0 : int 
    val STORE_1 : int 
    val STORE_2 : int 
    val STORE_3 : int 
    val STORE_N : int 
    val STACK_ADDR_INF_BIT : int 
    val STACK_ADDR : int 
    val ENV_TO_ACC : int 
    val IMMED_INT0 : int 
    val IMMED_INT1 : int 
    val IMMED_INT2 : int 
    val IMMED_INT3 : int 
    val IMMED_INT : int 
    val IMMED_STRING : int 
    val IMMED_REAL : int 
    val PUSH : int 
    val PUSH_LBL : int 
    val POP_1 : int 
    val POP_2 : int 
    val POP_N : int 
    val APPLY_FN_CALL : int 
    val APPLY_FN_JMP : int 
    val APPLY_FUN_CALL1 : int 
    val APPLY_FUN_CALL2 : int 
    val APPLY_FUN_CALL3 : int 
    val APPLY_FUN_CALL : int 
    val APPLY_FUN_JMP : int 
    val RETURN_1_1 : int 
    val RETURN_N_1 : int 
    val RETURN : int 
    val C_CALL0 : int 
    val C_CALL1 : int 
    val C_CALL2 : int 
    val C_CALL3 : int 
    val C_CALL4 : int 
    val LABEL : int 
    val JMP_REL : int 
    val IF_NOT_EQ_JMP_REL_IMMED3 : int 
    val IF_NOT_EQ_JMP_REL_IMMED : int 
    val IF_LESS_THAN_JMP_REL_IMMED : int 
    val IF_GREATER_THAN_JMP_REL_IMMED : int 
    val DOT_LABEL : int 
    val JMP_VECTOR : int 
    val RAISE : int 
    val PUSH_EXN_PTR : int 
    val POP_EXN_PTR : int 
    val GLOBAL_EXN_HANDLER_REPORT : int 
    val LETREGION_FIN : int 
    val LETREGION_INF : int 
    val ENDREGION_INF : int 
    val RESET_REGION : int 
    val MAYBE_RESET_REGION : int 
    val RESET_REGION_IF_INF : int 
    val FETCH_DATA : int 
    val STORE_DATA : int 
    val HALT : int 
    val STACK_OFFSET : int 
    val POP_PUSH : int 
    val IMMED_INT_PUSH0 : int 
    val IMMED_INT_PUSH1 : int 
    val IMMED_INT_PUSH2 : int 
    val IMMED_INT_PUSH3 : int 
    val IMMED_INT_PUSH : int 
    val SELECT_PUSH0 : int 
    val SELECT_PUSH1 : int 
    val SELECT_PUSH2 : int 
    val SELECT_PUSH3 : int 
    val SELECT_PUSH : int 
    val SELECT_ENV_PUSH : int 
    val SELECT_ENV_CLEAR_ATBOT_BIT_PUSH : int 
    val STACK_ADDR_PUSH : int 
    val STACK_ADDR_INF_BIT_ATBOT_BIT_PUSH : int 
    val SELECT_STACK_PUSH : int 
    val ENV_PUSH : int 
    val PRIM_EQUAL_I : int 
    val PRIM_SUB_I1 : int 
    val PRIM_SUB_I2 : int 
    val PRIM_SUB_I : int 
    val PRIM_ADD_I1 : int 
    val PRIM_ADD_I2 : int 
    val PRIM_ADD_I : int 
    val PRIM_MUL_I : int 
    val PRIM_NEG_I : int 
    val PRIM_ABS_I : int 
    val PRIM_ADD_F : int 
    val PRIM_SUB_F : int 
    val PRIM_MUL_F : int 
    val PRIM_DIV_F : int 
    val PRIM_NEG_F : int 
    val PRIM_ABS_F : int 
    val PRIM_LESS_THAN_F : int 
    val PRIM_LESS_EQUAL_F : int 
    val PRIM_GREATER_THAN_F : int 
    val PRIM_GREATER_EQUAL_F : int 
    val PRIM_LESS_THAN : int 
    val PRIM_LESS_EQUAL : int 
    val PRIM_GREATER_THAN : int 
    val PRIM_GREATER_EQUAL : int 
    val PRIM_LESS_THAN_UNSIGNED : int 
    val PRIM_GREATER_THAN_UNSIGNED : int 
    val PRIM_LESS_EQUAL_UNSIGNED : int 
    val PRIM_GREATER_EQUAL_UNSIGNED : int 
    val PRIM_AND_W : int 
    val PRIM_OR_W : int 
    val PRIM_XOR_W : int 
    val PRIM_SHIFT_LEFT_W : int 
    val PRIM_SHIFT_RIGHT_SIGNED_W : int 
    val PRIM_SHIFT_RIGHT_UNSIGNED_W : int 
    val PRIM_ADD_W : int 
    val PRIM_SUB_W : int 
    val PRIM_MUL_W : int 
    val PRIM_SUB_I31 : int 
    val PRIM_ADD_I31 : int 
    val PRIM_MUL_I31 : int 
    val PRIM_NEG_I31 : int 
    val PRIM_ABS_I31 : int 
    val PRIM_XOR_W31 : int 
    val PRIM_SHIFT_LEFT_W31 : int 
    val PRIM_SHIFT_RIGHT_SIGNED_W31 : int 
    val PRIM_SHIFT_RIGHT_UNSIGNED_W31 : int 
    val PRIM_ADD_W31 : int 
    val PRIM_SUB_W31 : int 
    val PRIM_MUL_W31 : int 
    val PRIM_I31_TO_I : int 
    val PRIM_I_TO_I31 : int 
    val PRIM_W31_TO_W : int 
    val PRIM_W_TO_W31 : int 
    val PRIM_W31_TO_W_X : int 
    val PRIM_W_TO_I : int 
    val PRIM_FRESH_EXNAME : int 
  end
