import
  ../Edlib/edlib.pm
  ../Pickle/pickle.pm
  ../Common/tools.pm
  ../Common/syntax_objects.pm
  ../Common/special_objects.pm
  compiler_objects.pm
  ../Common/basics.pm
  ../Manager/manager.pm
  compiler.pm
in
  Backend/Barry/COMP_BASIS_BARRY.sml
  Backend/Barry/CompBasisBarry.sml
  Backend/Barry/CompileBarry.sml
  Backend/Barry/CompileBasisBarry.sml
  Backend/Barry/ExecutionBarry.sml
  ../Common/KitBarry.sml
end
