import
  ../Edlib/edlib.pm
  ../Pickle/pickle.pm
  ../Common/tools.pm
  ../Common/syntax_objects.pm
  ../Common/special_objects.pm
  ../Common/basics.pm
in
  Lambda/LVARS.sml
  Lambda/CON.sml
  Lambda/EXCON.sml
  Regions/ADDRESS_LABELS.sml
  Lambda/Lvars.sml
  Lambda/Con.sml
  Lambda/Excon.sml
  Regions/AddressLabels.sml

  Lambda/COMPILER_ENV.sml
  Lambda/LAMBDA_EXP.sml
  Lambda/LambdaExp.sml
  Lambda/LAMBDA_BASICS.sml
  Lambda/LambdaBasics.sml
  Lambda/CompilerEnv.sml
end
