#
# The home of AOLserver
#
NSHOME ?= /usr/share/aolserver

#
# Module name
#
MOD      =  nsprof.so

#
# Objects to build
#
OBJS     =  nsprof.o

#
# Header files in THIS directory
#
HDRS     =  

#
# Extra libraries
#
MODLIBS  =

#
# Compiler flags
#
CFLAGS   =  

include $(NSHOME)/include/Makefile.module
