local
  ../lib/Quot.sml
  ../lib/HTML.sml
  ../lib/Html.sml
  local
    ../lib/NsBasics.sml
    ../lib/NS_SET.sml
    ../lib/NsSet.sml
    ../lib/NsInfo.sml
    ../lib/NS_DB.sml
    ../lib/DbFunctor.sml
  in
    ../lib/NS.sml
    ../lib/Ns.sml  
    ../lib/Db.sml
  end
  ../scs_lib/ScsLang.sml
  ../scs_lib/ScsDate.sml
  ../scs_lib/SCS_PAGE.sml
  ../scs_lib/ScsPage.sml
  ../scs_lib/ScsLogin.sml
  ../scs_lib/ScsList.sml
  ../scs_lib/ScsDict.sml
  ../lib/MSP.sml
  ../lib/Msp.sml
  ../scs_lib/ScsFormVar.sml

  rating/RatingUtil.sml
in
 [
  rating/index.sml
  rating/add.sml
  rating/add0.sml
  rating/wine.sml
  employee/update.sml
  employee/search.sml
  time_of_day.sml
  cache.sml
  cache_lookup.sml
  cache_add.sml
  guess.sml
  counter.sml
  temp.sml
  recipe.sml
  hej.sml
  yellow.sml
  hello.sml
  show.sml
  h1.sml
  hello.msp
  calendar.msp
  test.msp
  index.sml
  logtofile.msp
  fileindex.msp
  dir.msp
  friends.msp
  friends_add_form.msp
  friends_add.msp
  server.sml
  mail_form.sml
  mail.sml
  mul.msp

  cs_form.sml
  cs_add.sml
  cs_upd.sml
  cs_const.sml

  ug.sml
  currency.sml
  currency_cache.sml
  regexp.sml
  cookie.sml
  cookie_set.sml
  cookie_delete.sml

  formvar.sml
  formvar_chk.sml
  url_desc.sml

  auth_example.sml
  auth.sml
  auth_form.sml
  auth_logout.sml
  show_cookies.sml

  email_form.sml
  email_sent.sml
 ]
end
