#
# The home of AOLserver
#
#NSHOME ?= /home/mael/aol32-src/root/aolserver
NSHOME ?= /usr/share/aolserver

#
# Module name
#
MOD      =  nssml.so

#
# Objects to build
#
OBJS     =  nssml.o nssmllib.o HashTable.o

#
# Header files in THIS directory
#
HDRS     =  

#
# Extra libraries
#
MODLIBS  =  ../Runtime/runtimeSystemKamNsSml.o  

#
# Compiler flags
#
CFLAGS   =  

include $(NSHOME)/include/Makefile.module
