#
# The home of AOLserver
#
NSHOME ?= /home/mael/aol32-src/root/aolserver

#
# Module name
#
MOD      =  nssml.so

#
# Objects to build
#
OBJS     =  nssml.o nssmllib.o

#
# Header files in THIS directory
#
HDRS     =  

#
# Extra libraries
#
MODLIBS  =  ../RuntimeWithGC/runtimeSystemKAM.o  

#
# Compiler flags
#
CFLAGS   =  


include  $(NSHOME)/include/Makefile.module
