local
  ../lib/Quot.sml
  local
    ../lib/NsBasics.sml
    ../lib/NS_SET.sml
    ../lib/NsSet.sml
    ../lib/NsInfo.sml
    ../lib/NS_DB.sml
    ../lib/DbFunctor.sml
  in
    ../lib/NS.sml
    ../lib/Ns.sml  
    ../lib/Db.sml
    ../lib/DbClob.sml
  end

  ../lib/HTML.sml
  ../lib/Html.sml
  ../lib/MSP.sml
  ../lib/Msp.sml
  ../demo_lib/Page.sml
  ../demo_lib/FormVar.sml
  ../demo_lib/Login.sml

  ../demo_lib/RatingUtil.sml
in
 [
  rating/index.sml
  rating/add.sml
  rating/add0.sml
  rating/wine.sml
  employee/update.sml
  employee/search.sml
  time_of_day.sml
  cache.sml
  cache_lookup.sml
  cache_add.sml
  guess.sml
  counter.sml
  temp.sml
  recipe.sml
  hej.sml
  yellow.sml
  fib.sml
  life.sml
  hello.sml
  show.sml
  h1.sml
  hello.msp
  calendar.msp
  test.msp
  index.sml
  logtofile.msp
  fileindex.msp
  dir.msp
  friends.msp
  friends_add_form.msp
  friends_add.msp
  server.sml
  mail_form.sml
  mail.sml
  mul.msp
  show_cookies.sml
  auth_example.sml
  cs_form.sml
  cs_add.sml
  cs_upd.sml
  cs_const.sml
(*
  ug.sml
  currency.sml
*)
  currency_cache.sml
  regexp.sml
  cookie.sml
  cookie_set.sml
  cookie_delete.sml

  formvar.sml
  formvar_chk.sml
  url_desc.sml

  email_form.sml
  email_sent.sml

  auth_form.sml
  auth.sml
  link/index.sml
  link/add_form.sml
  link/add.sml
  link/delete.sml
 ]
end
