  Quot.sml
  local
    SMLSERVER_CACHE.sml
    SMLSERVER_COOKIE.sml
    SMLSERVER_MAIL.sml
    SMLSERVER_INFO.sml
    SMLSERVER_DB_HANDLE.sml
    SMLSERVER_DB.sml
    SMLSERVER_FORM.sml
    SMLSERVER_UNSAFE.sml
    NsBasics.sml
    NS_SET.sml
    NsSet.sml
    SMLserverForm.sml
    SMLserverDbFunctor.sml
    SMLserverUnsafe.sml
  in    
    SMLSERVER.sig
    SMLserver.sml  
  end

  local 
    XHTML_ATTR.sml
    XHtmlAttr.sml
  in
    XHTML.sig
    XHtml.sml
    HTTP.sig
    Http.sml
  end
