#!/usr/bin/perl

# get filename (without postfix) 
$filename = $ARGV[0];



# wc -l example
# 7 Add_eks.csv
@lc_out = split " ", `wc -l $filename.csv`;
$lines = $lc_out[0];


open (LOGFILE, "$filename.log");
# log file example excerpt
#Table TMP_ADD_EKS_1999_2:
#  7 Rows successfully loaded.
#  0 Rows not loaded due to data errors.
#  0 Rows not loaded because all WHEN clauses were failed.
#  0 Rows not loaded because all fields were null.

$succesfully = 0;
$not_loaded = 0;
while(<LOGFILE>){
  if (/(\d+) Row(s?) successfully/) {
      $succesfully += $1;
  }
  if (/(\d+) Row(s?) not loaded/) {
      $not_loaded += $1;
  }
}

$resultstr = "";
if ($lines == $succesfully){
    $resultstr .= "OK";
} else{
    $resultstr .= "NOT OK";
}
$resultstr .= " File $filename: ";
$resultstr .= " ($lines in $filename.csv, $succesfully loaded records, $not_loaded bad records )";
print STDOUT $resultstr."\n";  


