(* -----------------------------------------------------------
 * ML Kit script file.
 *
 * syntax: 
 *
 *   DEC   ::= val ID : TYPE = CONST <DEC>
 *   ID    ::= sequence_of_letters_underbars_and_primes
 *   TYPE  ::= int |  string  |  bool
 *   CONST ::= ml_integer_constant  |  ml_string_constant  
 *           | ml_bool_constant
 *
 *   blanks, tabs and newlines are separators;
 *   comments are enclosed in (* and *) and can be nested.
 * ----------------------------------------------------------- *)

val print_physical_size_inference_expression : bool = false
val print_types : bool = false
val report_file_sig : bool = false
val warn_on_escaping_puts : bool = true
val colwidth : int = 80
val maximum_inline_size : int = 20
val log_to_file : bool = true
val print_call_explicit_expression : bool = true
val print_drop_regions_expression : bool = false
val region_profiling : bool = false
val print_program_points : bool = false
val print_opt_lambda_expression : bool = false
